import re

original_data = [
    ["～である be", "be - was - been"],
    ["～させる let", "let - let - let"],
    ["支える bear", "bear - bore - borne"],
    ["横たわる lie", "lie - lay - lain"],
    ["打つ、負かす beat", "beat - beat - beaten"],
    ["なくす lose", "lose - lost - lost"],
    ["～になる become", "become - became - become"],
    ["作る make", "make - made - made"],
    ["始める begin", "begin - began - begun"],
    ["意味する mean", "mean - meant - meant"],
    ["噛む bite", "bite - bit - bitten"],
    ["会う meet", "meet - met - met"],
    ["吹く blow", "blow - blew - blown"],
    ["追い越す overtake", "overtake - overtook - overtaken"],
    ["壊す break", "break - broke - broken"],
    ["支払う pay", "pay - paid - paid"],
    ["持ってくる bring", "bring - brought - brought"],
    ["置く put", "put - put - put"],
    ["建てる build", "build - built - built"],
    ["読む read", "read - read - read"],
    ["燃やす burn", "burn - burnt - burnt"],
    ["乗る ride", "ride - rode - ridden"],
    ["買う buy", "buy - bought - bought"],
    ["ベルが鳴る ring", "ring - rang - rung"],
    ["つかむ catch", "catch - caught - caught"],
    ["上がる rise", "rise - rose - risen"],
    ["選ぶ choose", "choose - chose - chosen"],
    ["走る run", "run - ran - run"],
    ["来る come", "come - came - come"],
    ["言う say", "say - said - said"],
    ["費用がかかる cost", "cost - cost - cost"],
    ["見る see", "see - saw - seen"],
    ["切る cut", "cut - cut - cut"],
    ["売る sell", "sell - sold - sold"],
    ["掘る dig", "dig - dug - dug"],
    ["送る send", "send - sent - sent"],
    ["する do", "do - did - done"],
    ["置く set", "set - set - set"],
    ["描く draw", "draw - drew - drawn"],
    ["振る shake", "shake - shook - shaken"],
    ["飲む drink", "drink - drank - drunk"],
    ["発射する shoot", "shoot - shot - shot"],
    ["運転する drive", "drive - drove - driven"],
    ["見せる show", "show - showed - shown"],
    ["食べる eat", "eat - ate - eaten"],
    ["閉じる shut", "shut - shut - shut"],
    ["落ちる fall", "fall - fell - fallen"],
    ["歌う sing", "sing - sang - sung"],
    ["食べ物を与える feed", "feed - fed - fed"],
    ["沈む sink", "sink - sank - sunk"],
    ["感じる feel", "feel - felt - felt"],
    ["座る sit", "sit - sat - sat"],
    ["戦う fight", "fight - fought - fought"],
    ["眠っている sleep", "sleep - slept - slept"],
    ["捜して見つける find", "find - found - found"],
    ["話す speak", "speak - spoke - spoken"],
    ["忘れる forget", "forget - forgot - forgotten, forgot"],
    ["金を使う spend", "spend - spent - spent"],
    ["手に入れる get", "get - got - gotten"],
    ["広げる spread", "spread - spread - spread"],
    ["与える give", "give - gave - given"],
    ["立つ stand", "stand - stood - stood"],
    ["行く go", "go - went - gone"],
    ["盗む steal", "steal - stole - stolen"],
    ["育つ grow", "grow - grew - grown"],
    ["掃く sweep", "sweep - swept - swept"],
    ["掛ける hang", "hang - hung - hung"],
    ["泳ぐ swim", "swim - swam - swum"],
    ["持つ have", "have - had - had"],
    ["持って行く take", "take - took - taken"],
    ["聞える hear", "hear - heard - heard"],
    ["教える teach", "teach - taught - taught"],
    ["打つ hit", "hit - hit - hit"],
    ["言う、知らせる tell", "tell - told - told"],
    ["手でつかむ hold", "hold - held - held"],
    ["思う、考える think", "think - thought - thought"],
    ["傷つける hurt", "hurt - hurt - hurt"],
    ["投げる throw", "throw - threw - thrown"],
    ["保つ keep", "keep - kept - kept"],
    ["理解する understand", "understand - understood - understood"],
    ["知っている know", "know - knew - known"],
    ["目が覚める wake", "wake - woke - woken"],
    ["横たえる lay", "lay - laid - laid"],
    ["身につける wear", "wear - wore - worn"],
    ["導く lead", "lead - led - led"],
    ["勝つ win", "win - won - won"],
    ["去る leave", "leave - left - left"],
    ["書く write", "write - wrote - written"],
    ["貸す lend", "lend - lent - lent"]
]

sorted_data = [
  ["～である be", "be - was - been"],
  ["～になる become", "become - became - become"],
  ["打つ、負かす beat", "beat - beat - beaten"],
  ["支える bear", "bear - bore - borne"],
  ["始める begin", "begin - began - begun"],
  ["噛む bite", "bite - bit - bitten"],
  ["吹く blow", "blow - blew - blown"],
  ["壊す break", "break - broke - broken"],
  ["持ってくる bring", "bring - brought - brought"],
  ["建てる build", "build - built - built"],
  ["燃やす burn", "burn - burnt - burnt"],
  ["買う buy", "buy - bought - bought"],
  ["つかむ catch", "catch - caught - caught"],
  ["選ぶ choose", "choose - chose - chosen"],
  ["来る come", "come - came - come"],
  ["費用がかかる cost", "cost - cost - cost"],
  ["切る cut", "cut - cut - cut"],
  ["掘る dig", "dig - dug - dug"],
  ["する do", "do - did - done"],
  ["描く draw", "draw - drew - drawn"],
  ["飲む drink", "drink - drank - drunk"],
  ["運転する drive", "drive - drove - driven"],
  ["食べる eat", "eat - ate - eaten"],
  ["感じる feel", "feel - felt - felt"],
  ["食べ物を与える feed", "feed - fed - fed"],
  ["捜して見つける find", "find - found - found"],
  ["戦う fight", "fight - fought - fought"],
  ["落ちる fall", "fall - fell - fallen"],
  ["忘れる forget", "forget - forgot - forgotten, forgot"],
  ["手に入れる get", "get - got - gotten"],
  ["与える give", "give - gave - given"],
  ["行く go", "go - went - gone"],
  ["育つ grow", "grow - grew - grown"],
  ["掛ける hang", "hang - hung - hung"],
  ["持つ have", "have - had - had"],
  ["聞える hear", "hear - heard - heard"],
  ["打つ hit", "hit - hit - hit"],
  ["手でつかむ hold", "hold - held - held"],
  ["傷つける hurt", "hurt - hurt - hurt"],
  ["保つ keep", "keep - kept - kept"],
  ["知っている know", "know - knew - known"],
  ["横たえる lay", "lay - laid - laid"],
  ["導く lead", "lead - led - led"],
  ["去る leave", "leave - left - left"],
  ["貸す lend", "lend - lent - lent"],
  ["～させる let", "let - let - let"],
  ["横たわる lie", "lie - lay - lain"],
  ["なくす lose", "lose - lost - lost"],
  ["作る make", "make - made - made"],
  ["意味する mean", "mean - meant - meant"],
  ["会う meet", "meet - met - met"],
  ["追い越す overtake", "overtake - overtook - overtaken"],
  ["支払う pay", "pay - paid - paid"],
  ["置く put", "put - put - put"],
  ["読む read", "read - read - read"],
  ["乗る ride", "ride - rode - ridden"],
  ["ベルが鳴る ring", "ring - rang - rung"],
  ["上がる rise", "rise - rose - risen"],
  ["走る run", "run - ran - run"],
  ["言う say", "say - said - said"],
  ["見る see", "see - saw - seen"],
  ["売る sell", "sell - sold - sold"],
  ["送る send", "send - sent - sent"],
  ["置く set", "set - set - set"],
  ["振る shake", "shake - shook - shaken"],
  ["発射する shoot", "shoot - shot - shot"],
  ["見せる show", "show - showed - shown"],
  ["閉じる shut", "shut - shut - shut"],
  ["歌う sing", "sing - sang - sung"],
  ["沈む sink", "sink - sank - sunk"],
  ["座る sit", "sit - sat - sat"],
  ["眠っている sleep", "sleep - slept - slept"],
  ["話す speak", "speak - spoke - spoken"],
  ["費やす spend", "spend - spent - spent"],
  ["広げる spread", "spread - spread - spread"],
  ["立つ stand", "stand - stood - stood"],
  ["盗む steal", "steal - stole - stolen"],
  ["掃く sweep", "sweep - swept - swept"],
  ["泳ぐ swim", "swim - swam - swum"],
  ["持って行く take", "take - took - taken"],
  ["教える teach", "teach - taught - taught"],
  ["言う、知らせる tell", "tell - told - told"],
  ["思う、考える think", "think - thought - thought"],
  ["投げる throw", "throw - threw - thrown"],
  ["理解する understand", "understand - understood - understood"],
  ["目が覚める wake", "wake - woke - woken"],
  ["身につける wear", "wear - wore - worn"],
  ["勝つ win", "win - won - won"],
  ["書く write", "write - wrote - written"]
]



# 動詞の原形を抽出する関数（最初の英単語を取り出す）
def extract_base_verb(entry):
    # 例: ["～である be", "be - was - been"] → "be"
    match = re.match(r"([a-z]+)", entry[1])
    return match.group(1) if match else None

# 元データとソート済みデータの動詞の原形セットを作成
original_base_verbs = set(extract_base_verb(item) for item in original_data if extract_base_verb(item))
sorted_base_verbs = set(extract_base_verb(item) for item in sorted_data if extract_base_verb(item))

# 欠落している動詞の原形を取得
missing_base_verbs = original_base_verbs - sorted_base_verbs

# 元データから、欠落した原形動詞に対応するエントリを抽出
missing_entries = [item for item in original_data if extract_base_verb(item) in missing_base_verbs]

print(len(missing_entries))